/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package steganografie;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import static steganografie.Cititor.citBit;
import static steganografie.ImagineDigitala.DIM;
import static steganografie.TextPDF.actCod;
import static steganografie.TextPDF.capacitate;
import static steganografie.TextPDF.cod;
import static steganografie.TextPDF.fontSize;
import static steganografie.TextPDF.totBitiAntet;

public class Interfata extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Interfata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCapacitate = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabelFisierPoza = new javax.swing.JLabel();
        jButtonCodificaEZW = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldBPP = new javax.swing.JTextField();
        jButtonDecodificaEZW = new javax.swing.JButton();
        jLabelPoza = new javax.swing.JLabel();
        jLabelStare = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabelCapacitate.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton7.setText("1. Capacitate");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("2. Citeste poza");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabelFisierPoza.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonCodificaEZW.setText("3. Codifica EZW scrie în PDF");
        jButtonCodificaEZW.setEnabled(false);
        jButtonCodificaEZW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCodificaEZWActionPerformed(evt);
            }
        });

        jLabel12.setText("bpp:");

        jTextFieldBPP.setText("0.5");
        jTextFieldBPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBPPActionPerformed(evt);
            }
        });

        jButtonDecodificaEZW.setText("4. Decodifica EZW citeste din PDF");
        jButtonDecodificaEZW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecodificaEZWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCapacitate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFisierPoza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonCodificaEZW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDecodificaEZW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBPP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCapacitate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFisierPoza, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCodificaEZW, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldBPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDecodificaEZW, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jLabelStare.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelStare.setForeground(new java.awt.Color(255, 51, 51));
        jLabelStare.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelStare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPoza, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStare, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPoza, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Calculează capacitatea
        try {
            JFileChooser jfc=new JFileChooser(System.getProperty("user.dir"));
            jfc.showOpenDialog(this);
            File f=jfc.getSelectedFile(); 
            if(f==null)
                return;
            //jLabel2.setText(f.getName());
            
            String[] lines;
            
            PDDocument document = PDDocument.load(f);
            PDFTextStripper stripper = new PDFTextStripper();
            String text = stripper.getText(document);
            lines = text.split(System.getProperty("line.separator"));
            document.close();
            
            StringBuffer caractere=new StringBuffer();
            
            for(String linie : lines){
                linie=linie.replaceAll("[ ]+", " ");//elimin spațiile multiple
                if(linie.contains("  "))//asta nu trebuie să mai apară!!!!
                   System.out.println("mai multe spatii");
               
                //System.out.println(linie);
                caractere.append(linie+'\n');
            }
            
            TextPDF tpdf=new TextPDF(caractere+"", true);
            jLabelCapacitate.setText("Bitrate maxim: "+((capacitate-32*4)*3./512/512)+" [bpp] ");
            
        } catch (IOException ex) {
            Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed
File pozaSelectata;
ImagineDigitala id;
String fisierPoza="";
void citestePozaSelectata(){
        try {
            fisierPoza=pozaSelectata.getAbsolutePath();
            jLabelFisierPoza.setText(fisierPoza);
            id=new ImagineDigitala(fisierPoza, this);
            id.afiseaza(id.pixeliImagine, jLabelPoza);
        } catch (InterruptedException ex) {
            Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Citeste poza
        JFileChooser jfc=new JFileChooser(System.getProperty("user.dir"));
        jfc.setFileFilter(new Filtru());
        jfc.showOpenDialog(this);
        //String fisierIesire=jfc.getSelectedFile().getAbsolutePath();
        //fisierPoza=jfc.getName(jfc.getSelectedFile());
        pozaSelectata=jfc.getSelectedFile();
        if(pozaSelectata==null){
            //jButton1.setEnabled(false);
            return;
        }
        //jButton1.setEnabled(true);
        citestePozaSelectata();
        jButtonCodificaEZW.setEnabled(true);
        //jLabelErori.setText("Poza aleasa.");                                                
    }//GEN-LAST:event_jButton8ActionPerformed

    EZW ezwY, ezwC1, ezwC2;
    private void jButtonCodificaEZWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCodificaEZWActionPerformed
        // Codificare EZW:
        float bpp=Float.parseFloat(jTextFieldBPP.getText());
        

        ezwY=new EZW(id.y,DIM,bpp/2);
        ezwC1=new EZW(id.c1,DIM/2,bpp/4);
        ezwC2=new EZW(id.c2,DIM/2,bpp/4);
        //tablourile c1 și c2 sunt de 4 ori mai mici decât y.

        ezwY.desc();
        ezwC1.desc();
        ezwC2.desc();
        scrieEZWInPDF();
        
    }//GEN-LAST:event_jButtonCodificaEZWActionPerformed

    int[] antet=new int[totBitiAntet];
    int nrBitAntet;
    
    int citesteA(){
        int masca;
        int rez=0;
        for(int i=0; i<32; i++){
            masca=0x80000000>>>i;
            if(antet[nrBitAntet]==1)
                rez|=masca;
            nrBitAntet++;
        }
        return rez;
    }
    
    int pragInitialY, nrTotalBitiY, mediaY, DIMY;   //    bariabile
    int pragInitialC1, nrTotalBitiC1, mediaC1, DIMC1; //  necesare
    int pragInitialC2, nrTotalBitiC2, mediaC2, DIMC2; // la codificare
    
    void preiaAntetul(){ 
        //System.out.println("\n=====================");
        try {
           // nrBitAntet=0;
            for(int i=0; i<totBitiAntet; i++){
                antet[i]=citBit();
                //System.out.println("----"+antet[i]);
            }
    
            nrBitAntet=0;
            
            pragInitialY=citesteA();
            DIMY=citesteA();
            nrTotalBitiY=citesteA();
            mediaY=citesteA();
            
            pragInitialC1=citesteA();
            DIMC1=citesteA();
            nrTotalBitiC1=citesteA();
            mediaC1=citesteA();
            
            pragInitialC2=citesteA();
            DIMC2=citesteA();
            nrTotalBitiC2=citesteA();
            mediaC2=citesteA();

            //for(int i:antet)
            //    System.out.println(i);
        } catch (GataCitBiti ex) {
            Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jButtonDecodificaEZWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecodificaEZWActionPerformed
            // Decodifica EZW

        
        citesteEZWDinPDF();
        
        //ezwY=new EZW();
        //ezwC1=new EZW();
        //ezwC2=new EZW();
        
        preiaAntetul();

        //ezwY.initTab();
        //ezwC1.initTab();
        //ezwC2.initTab();

        id=new ImagineDigitala(this);
       //EZWInv(float[][]tab, int pragInitial, int DIM, int nrTotalBiti, int media){
    //this.ezw=ezw; 
        new EZWInv(id.y, pragInitialY, DIMY, nrTotalBitiY, mediaY).ref();
        //System.out.println("gataY");
        new EZWInv(id.c1, pragInitialC1, DIMC1, nrTotalBitiC1, mediaC1).ref();
        //new EZWInv(ezwC1).ref();
        //System.out.println("gataC1");
         new EZWInv(id.c2, pragInitialC2, DIMC2, nrTotalBitiC2, mediaC2).ref();
        //new EZWInv(ezwC2).ref();
        //System.out.println("GataC2");

        
        
        id.compuneCulori(false);
        id.afiseaza(id.pixeliImagine, jLabelPoza);
        jLabelStare.setText("Operație încheiată");
        jButtonCodificaEZW.setEnabled(true);
    }//GEN-LAST:event_jButtonDecodificaEZWActionPerformed

    private void jTextFieldBPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBPPActionPerformed

    void citesteEZWDinPDF(){
        try {
            JFileChooser jfc=new JFileChooser(System.getProperty("user.dir"));
            jfc.showOpenDialog(this);
            File f=jfc.getSelectedFile();
            if(f==null)
                return;
            //jLabel2.setText(f.getName());
            jLabelStare.setText("Așteptați, preiau poza din fișierul "+f.getName());
            super.update(this.getGraphics());
             
            String fisierPDF=f.getAbsolutePath();
            new Cititor(fisierPDF).citeste();
        } catch (IOException ex) {
            Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    void scrieEZWInPDF(){
        try {
            JFileChooser jfc=new JFileChooser(System.getProperty("user.dir"));
            jfc.showOpenDialog(this);
            File f=jfc.getSelectedFile(); 
            if(f==null)
                return;
            //jLabel2.setText(f.getName());
            jLabelStare.setText("Așteptați, scriu datele în fisierul"+f.getName());
            
            
            //SwingUtilities.updateComponentTreeUI(this);
            //invalidate();
            //validate();
            //repaint();

           // SwingUtilities.updateComponentTreeUI(jLabelStare);
            //jLabelStare.invalidate();
            //jLabelStare.validate();
            //jLabelStare.repaint();
            
            super.update(this.getGraphics());
            
            String[] lines;
            
            PDDocument document = PDDocument.load(f);
            PDFTextStripper stripper = new PDFTextStripper();
            String text = stripper.getText(document);
            lines = text.split(System.getProperty("line.separator"));
            document.close();
            
            StringBuffer caractere=new StringBuffer();
            
            for(String linie : lines){
                linie=linie.replaceAll("[ ]+", " ");//elimin spațiile multiple
                if(linie.contains("  "))
                   System.out.println("mai multe spatii");
               
                //System.out.println(linie);
                caractere.append(linie+'\n');
            }
            
            TextPDF tpdf=new TextPDF(caractere+"", ezwY, ezwC1, ezwC2);
            //tpdf.afiseaza();
            //tpdf.incheieLiniile();

            tpdf.scrieFisierPDF();
   
        } catch (IOException ex) {
            Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabelStare.setText("Operație încheiată"); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonCodificaEZW;
    private javax.swing.JButton jButtonDecodificaEZW;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabelCapacitate;
    private javax.swing.JLabel jLabelFisierPoza;
    private javax.swing.JLabel jLabelPoza;
    private javax.swing.JLabel jLabelStare;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBPP;
    // End of variables declaration//GEN-END:variables
}
